import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_share_blocks_image_pins_pins_pin_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  CREATE TYPE "public"."enum_pages_blocks_image_pins_pins_pin_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  CREATE TYPE "public"."enum__pages_v_blocks_image_pins_pins_pin_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  CREATE TYPE "public"."enum_flDet_blocks_image_pins_pins_pin_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  CREATE TYPE "public"."enum_newsDet_blocks_image_pins_pins_pin_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  ALTER TYPE "public"."enum_share_blocks_banner_banner_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_features_features_settings_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_gallery_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_img_content_accordion_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_map_pins_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_banner_banner_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_features_features_settings_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_gallery_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_map_pins_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_gallery_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_map_pins_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_globalheader_nav_items_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_globalheader_cta_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_globalfooter_bottom_links_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flats_gallery_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_banner_banner_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_gallery_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_map_pins_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_gallery_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_map_pins_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'metro' BEFORE 'download';
  ALTER TABLE "share_blocks_image_pins_pins" ADD COLUMN "pin_position" "enum_share_blocks_image_pins_pins_pin_position";
  ALTER TABLE "pages_blocks_image_pins_pins" ADD COLUMN "pin_position" "enum_pages_blocks_image_pins_pins_pin_position";
  ALTER TABLE "_pages_v_blocks_image_pins_pins" ADD COLUMN "pin_position" "enum__pages_v_blocks_image_pins_pins_pin_position";
  ALTER TABLE "flDet_blocks_image_pins_pins" ADD COLUMN "pin_position" "enum_flDet_blocks_image_pins_pins_pin_position";
  ALTER TABLE "newsDet_blocks_image_pins_pins" ADD COLUMN "pin_position" "enum_newsDet_blocks_image_pins_pins_pin_position";
  ALTER TABLE "share_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_height";
  ALTER TABLE "pages_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_height";
  ALTER TABLE "_pages_v_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_height";
  ALTER TABLE "flDet_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_height";
  ALTER TABLE "newsDet_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_height";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "share_blocks_image_pins_pins" ADD COLUMN "pin_height" numeric;
  ALTER TABLE "pages_blocks_image_pins_pins" ADD COLUMN "pin_height" numeric;
  ALTER TABLE "_pages_v_blocks_image_pins_pins" ADD COLUMN "pin_height" numeric;
  ALTER TABLE "flDet_blocks_image_pins_pins" ADD COLUMN "pin_height" numeric;
  ALTER TABLE "newsDet_blocks_image_pins_pins" ADD COLUMN "pin_height" numeric;
  ALTER TABLE "share_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_position";
  ALTER TABLE "pages_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_position";
  ALTER TABLE "_pages_v_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_position";
  ALTER TABLE "flDet_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_position";
  ALTER TABLE "newsDet_blocks_image_pins_pins" DROP COLUMN IF EXISTS "pin_position";
  ALTER TABLE "public"."share_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum_share_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum_share_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum_share_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."share_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum_share_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."share_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum_share_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."share_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum_share_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum_share_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum_share_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."share_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum_share_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."share_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum_share_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_share_blocks_gallery_link_icon" USING "link_icon"::"public"."enum_share_blocks_gallery_link_icon";
  ALTER TABLE "public"."share_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum_share_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."share_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum_share_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."share_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum_share_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."share_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum_share_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."share_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum_share_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum_share_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum_share_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."share_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_map_pins_icon";
  CREATE TYPE "public"."enum_share_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_share_blocks_map_pins_icon" USING "icon"::"public"."enum_share_blocks_map_pins_icon";
  ALTER TABLE "public"."share_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum_share_blocks_news_snippets_news_set_link_icon";
  ALTER TABLE "public"."pages_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum_pages_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum_pages_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum_pages_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."pages_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum_pages_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."pages_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum_pages_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."pages_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum_pages_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum_pages_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."pages_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum_pages_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."pages_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_pages_blocks_gallery_link_icon" USING "link_icon"::"public"."enum_pages_blocks_gallery_link_icon";
  ALTER TABLE "public"."pages_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum_pages_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."pages_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum_pages_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."pages_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum_pages_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."pages_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum_pages_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."pages_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum_pages_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."pages_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_map_pins_icon";
  CREATE TYPE "public"."enum_pages_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_map_pins_icon" USING "icon"::"public"."enum_pages_blocks_map_pins_icon";
  ALTER TABLE "public"."pages_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum_pages_blocks_news_snippets_news_set_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum__pages_v_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."_pages_v_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum__pages_v_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."_pages_v_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum__pages_v_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."_pages_v_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum__pages_v_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_gallery_link_icon" USING "link_icon"::"public"."enum__pages_v_blocks_gallery_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum__pages_v_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."_pages_v_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."_pages_v_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum__pages_v_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_map_pins_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_map_pins_icon" USING "icon"::"public"."enum__pages_v_blocks_map_pins_icon";
  ALTER TABLE "public"."_pages_v_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum__pages_v_blocks_news_snippets_news_set_link_icon";
  ALTER TABLE "public"."globalheader_nav_items" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_globalheader_nav_items_link_icon";
  CREATE TYPE "public"."enum_globalheader_nav_items_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."globalheader_nav_items" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_globalheader_nav_items_link_icon" USING "link_icon"::"public"."enum_globalheader_nav_items_link_icon";
  ALTER TABLE "public"."globalheader_cta_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_globalheader_cta_buttons_link_icon";
  CREATE TYPE "public"."enum_globalheader_cta_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."globalheader_cta_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_globalheader_cta_buttons_link_icon" USING "link_icon"::"public"."enum_globalheader_cta_buttons_link_icon";
  ALTER TABLE "public"."globalfooter_bottom_links" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_globalfooter_bottom_links_link_icon";
  CREATE TYPE "public"."enum_globalfooter_bottom_links_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."globalfooter_bottom_links" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_globalfooter_bottom_links_link_icon" USING "link_icon"::"public"."enum_globalfooter_bottom_links_link_icon";
  ALTER TABLE "public"."flatsstoone" ALTER COLUMN "gallery_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flats_gallery_link_icon";
  CREATE TYPE "public"."enum_flats_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flatsstoone" ALTER COLUMN "gallery_link_icon" SET DATA TYPE "public"."enum_flats_gallery_link_icon" USING "gallery_link_icon"::"public"."enum_flats_gallery_link_icon";
  ALTER TABLE "public"."flDet_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum_flDet_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."flDet_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum_flDet_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."flDet_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum_flDet_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum_flDet_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum_flDet_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."flDet_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum_flDet_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."flDet_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum_flDet_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."flDet_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum_flDet_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."flDet_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."flDet_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_flDet_blocks_gallery_link_icon" USING "link_icon"::"public"."enum_flDet_blocks_gallery_link_icon";
  ALTER TABLE "public"."flDet_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum_flDet_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."flDet_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum_flDet_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."flDet_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum_flDet_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."flDet_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_map_pins_icon";
  CREATE TYPE "public"."enum_flDet_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_flDet_blocks_map_pins_icon" USING "icon"::"public"."enum_flDet_blocks_map_pins_icon";
  ALTER TABLE "public"."flDet_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum_flDet_blocks_news_snippets_news_set_link_icon";
  ALTER TABLE "public"."newsDet_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum_newsDet_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."newsDet_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum_newsDet_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."newsDet_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum_newsDet_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."newsDet_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum_newsDet_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."newsDet_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."newsDet_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_gallery_link_icon" USING "link_icon"::"public"."enum_newsDet_blocks_gallery_link_icon";
  ALTER TABLE "public"."newsDet_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum_newsDet_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."newsDet_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."newsDet_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."newsDet_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."newsDet_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum_newsDet_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."newsDet_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_map_pins_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_newsDet_blocks_map_pins_icon" USING "icon"::"public"."enum_newsDet_blocks_map_pins_icon";
  ALTER TABLE "public"."newsDet_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum_newsDet_blocks_news_snippets_news_set_link_icon";
  DROP TYPE "public"."enum_share_blocks_image_pins_pins_pin_position";
  DROP TYPE "public"."enum_pages_blocks_image_pins_pins_pin_position";
  DROP TYPE "public"."enum__pages_v_blocks_image_pins_pins_pin_position";
  DROP TYPE "public"."enum_flDet_blocks_image_pins_pins_pin_position";
  DROP TYPE "public"."enum_newsDet_blocks_image_pins_pins_pin_position";`)
}
