import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_share_blocks_map_pins_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  CREATE TYPE "public"."enum_share_blocks_map_pins_color" AS ENUM('light', 'dark', 'yellow', 'green');
  CREATE TYPE "public"."enum_pages_blocks_map_pins_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  CREATE TYPE "public"."enum_pages_blocks_map_pins_color" AS ENUM('light', 'dark', 'yellow', 'green');
  CREATE TYPE "public"."enum__pages_v_blocks_map_pins_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  CREATE TYPE "public"."enum__pages_v_blocks_map_pins_color" AS ENUM('light', 'dark', 'yellow', 'green');
  CREATE TYPE "public"."enum_flDet_blocks_map_pins_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  CREATE TYPE "public"."enum_flDet_blocks_map_pins_color" AS ENUM('light', 'dark', 'yellow', 'green');
  CREATE TYPE "public"."enum_newsDet_blocks_map_pins_position" AS ENUM('left-down', 'left-up', 'right-down', 'right-up');
  CREATE TYPE "public"."enum_newsDet_blocks_map_pins_color" AS ENUM('light', 'dark', 'yellow', 'green');
  ALTER TYPE "public"."enum_share_blocks_banner_banner_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_banner_banner_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_banner_banner_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_banner_banner_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_settings_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_settings_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_settings_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_features_features_settings_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_gallery_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_gallery_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_gallery_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_gallery_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_img_content_accordion_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_img_content_accordion_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_img_content_accordion_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_img_content_accordion_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_map_pins_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_map_pins_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_map_pins_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_map_pins_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_banner_banner_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_banner_banner_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_banner_banner_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_banner_banner_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_settings_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_settings_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_settings_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_features_features_settings_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_gallery_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_gallery_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_gallery_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_gallery_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_map_pins_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_map_pins_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_map_pins_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_map_pins_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_gallery_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_gallery_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_gallery_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_gallery_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_map_pins_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_map_pins_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_map_pins_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_map_pins_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalheader_nav_items_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalheader_nav_items_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalheader_nav_items_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalheader_nav_items_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalheader_cta_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalheader_cta_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalheader_cta_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalheader_cta_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalfooter_bottom_links_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalfooter_bottom_links_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalfooter_bottom_links_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_globalfooter_bottom_links_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flats_gallery_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flats_gallery_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flats_gallery_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flats_gallery_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_banner_banner_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_banner_banner_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_banner_banner_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_banner_banner_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_gallery_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_gallery_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_gallery_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_gallery_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_map_pins_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_map_pins_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_map_pins_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_map_pins_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_gallery_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_gallery_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_gallery_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_gallery_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_map_pins_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_map_pins_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_map_pins_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_map_pins_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'leaf' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'lightBulb' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'drop' BEFORE 'phone';
  ALTER TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon" ADD VALUE 'flash' BEFORE 'phone';
  ALTER TABLE "share_blocks_features_features_with_title" ADD COLUMN "feature_title_content" jsonb;
  ALTER TABLE "share_blocks_map_pins" ADD COLUMN "marker_label" jsonb;
  ALTER TABLE "share_blocks_map_pins" ADD COLUMN "position" "enum_share_blocks_map_pins_position";
  ALTER TABLE "share_blocks_map_pins" ADD COLUMN "color" "enum_share_blocks_map_pins_color";
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_square_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_square_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_square_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_square_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_square_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_square_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_small_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_small_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_small_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_small_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_small_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_small_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_large_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_large_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_large_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_large_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_large_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_large_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_og_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_og_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_og_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_og_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_og_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_og_filename" varchar;
  ALTER TABLE "pages_blocks_features_features_with_title" ADD COLUMN "feature_title_content" jsonb;
  ALTER TABLE "pages_blocks_map_pins" ADD COLUMN "marker_label" jsonb;
  ALTER TABLE "pages_blocks_map_pins" ADD COLUMN "position" "enum_pages_blocks_map_pins_position";
  ALTER TABLE "pages_blocks_map_pins" ADD COLUMN "color" "enum_pages_blocks_map_pins_color";
  ALTER TABLE "_pages_v_blocks_features_features_with_title" ADD COLUMN "feature_title_content" jsonb;
  ALTER TABLE "_pages_v_blocks_map_pins" ADD COLUMN "marker_label" jsonb;
  ALTER TABLE "_pages_v_blocks_map_pins" ADD COLUMN "position" "enum__pages_v_blocks_map_pins_position";
  ALTER TABLE "_pages_v_blocks_map_pins" ADD COLUMN "color" "enum__pages_v_blocks_map_pins_color";
  ALTER TABLE "flDet_blocks_features_features_with_title" ADD COLUMN "feature_title_content" jsonb;
  ALTER TABLE "flDet_blocks_map_pins" ADD COLUMN "marker_label" jsonb;
  ALTER TABLE "flDet_blocks_map_pins" ADD COLUMN "position" "enum_flDet_blocks_map_pins_position";
  ALTER TABLE "flDet_blocks_map_pins" ADD COLUMN "color" "enum_flDet_blocks_map_pins_color";
  ALTER TABLE "newsDet_blocks_features_features_with_title" ADD COLUMN "feature_title_content" jsonb;
  ALTER TABLE "newsDet_blocks_map_pins" ADD COLUMN "marker_label" jsonb;
  ALTER TABLE "newsDet_blocks_map_pins" ADD COLUMN "position" "enum_newsDet_blocks_map_pins_position";
  ALTER TABLE "newsDet_blocks_map_pins" ADD COLUMN "color" "enum_newsDet_blocks_map_pins_color";
  CREATE INDEX IF NOT EXISTS "media_sizes_thumbnail_sizes_thumbnail_filename_idx" ON "media" USING btree ("sizes_thumbnail_filename");
  CREATE INDEX IF NOT EXISTS "media_sizes_square_sizes_square_filename_idx" ON "media" USING btree ("sizes_square_filename");
  CREATE INDEX IF NOT EXISTS "media_sizes_small_sizes_small_filename_idx" ON "media" USING btree ("sizes_small_filename");
  CREATE INDEX IF NOT EXISTS "media_sizes_medium_sizes_medium_filename_idx" ON "media" USING btree ("sizes_medium_filename");
  CREATE INDEX IF NOT EXISTS "media_sizes_large_sizes_large_filename_idx" ON "media" USING btree ("sizes_large_filename");
  CREATE INDEX IF NOT EXISTS "media_sizes_xlarge_sizes_xlarge_filename_idx" ON "media" USING btree ("sizes_xlarge_filename");
  CREATE INDEX IF NOT EXISTS "media_sizes_og_sizes_og_filename_idx" ON "media" USING btree ("sizes_og_filename");
  ALTER TABLE "share_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title";
  ALTER TABLE "pages_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title";
  ALTER TABLE "_pages_v_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title";
  ALTER TABLE "flDet_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title";
  ALTER TABLE "newsDet_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP INDEX IF EXISTS "media_sizes_thumbnail_sizes_thumbnail_filename_idx";
  DROP INDEX IF EXISTS "media_sizes_square_sizes_square_filename_idx";
  DROP INDEX IF EXISTS "media_sizes_small_sizes_small_filename_idx";
  DROP INDEX IF EXISTS "media_sizes_medium_sizes_medium_filename_idx";
  DROP INDEX IF EXISTS "media_sizes_large_sizes_large_filename_idx";
  DROP INDEX IF EXISTS "media_sizes_xlarge_sizes_xlarge_filename_idx";
  DROP INDEX IF EXISTS "media_sizes_og_sizes_og_filename_idx";
  ALTER TABLE "share_blocks_features_features_with_title" ADD COLUMN "feature_title" varchar;
  ALTER TABLE "pages_blocks_features_features_with_title" ADD COLUMN "feature_title" varchar;
  ALTER TABLE "_pages_v_blocks_features_features_with_title" ADD COLUMN "feature_title" varchar;
  ALTER TABLE "flDet_blocks_features_features_with_title" ADD COLUMN "feature_title" varchar;
  ALTER TABLE "newsDet_blocks_features_features_with_title" ADD COLUMN "feature_title" varchar;
  ALTER TABLE "share_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title_content";
  ALTER TABLE "share_blocks_map_pins" DROP COLUMN IF EXISTS "marker_label";
  ALTER TABLE "share_blocks_map_pins" DROP COLUMN IF EXISTS "position";
  ALTER TABLE "share_blocks_map_pins" DROP COLUMN IF EXISTS "color";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_filename";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_square_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_square_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_square_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_square_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_square_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_square_filename";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_small_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_small_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_small_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_small_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_small_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_small_filename";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_medium_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_medium_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_medium_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_medium_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_medium_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_medium_filename";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_large_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_large_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_large_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_large_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_large_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_large_filename";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_xlarge_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_xlarge_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_xlarge_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_xlarge_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_xlarge_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_xlarge_filename";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_filename";
  ALTER TABLE "pages_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title_content";
  ALTER TABLE "pages_blocks_map_pins" DROP COLUMN IF EXISTS "marker_label";
  ALTER TABLE "pages_blocks_map_pins" DROP COLUMN IF EXISTS "position";
  ALTER TABLE "pages_blocks_map_pins" DROP COLUMN IF EXISTS "color";
  ALTER TABLE "_pages_v_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title_content";
  ALTER TABLE "_pages_v_blocks_map_pins" DROP COLUMN IF EXISTS "marker_label";
  ALTER TABLE "_pages_v_blocks_map_pins" DROP COLUMN IF EXISTS "position";
  ALTER TABLE "_pages_v_blocks_map_pins" DROP COLUMN IF EXISTS "color";
  ALTER TABLE "flDet_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title_content";
  ALTER TABLE "flDet_blocks_map_pins" DROP COLUMN IF EXISTS "marker_label";
  ALTER TABLE "flDet_blocks_map_pins" DROP COLUMN IF EXISTS "position";
  ALTER TABLE "flDet_blocks_map_pins" DROP COLUMN IF EXISTS "color";
  ALTER TABLE "newsDet_blocks_features_features_with_title" DROP COLUMN IF EXISTS "feature_title_content";
  ALTER TABLE "newsDet_blocks_map_pins" DROP COLUMN IF EXISTS "marker_label";
  ALTER TABLE "newsDet_blocks_map_pins" DROP COLUMN IF EXISTS "position";
  ALTER TABLE "newsDet_blocks_map_pins" DROP COLUMN IF EXISTS "color";
  ALTER TABLE "public"."share_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum_share_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum_share_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum_share_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."share_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_share_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum_share_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."share_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_share_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum_share_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."share_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum_share_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum_share_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum_share_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."share_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum_share_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum_share_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."share_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum_share_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_share_blocks_gallery_link_icon" USING "link_icon"::"public"."enum_share_blocks_gallery_link_icon";
  ALTER TABLE "public"."share_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_share_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum_share_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."share_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_share_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum_share_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."share_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum_share_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum_share_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."share_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_share_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum_share_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."share_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum_share_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum_share_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum_share_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."share_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_map_pins_icon";
  CREATE TYPE "public"."enum_share_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_share_blocks_map_pins_icon" USING "icon"::"public"."enum_share_blocks_map_pins_icon";
  ALTER TABLE "public"."share_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."share_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum_share_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum_share_blocks_news_snippets_news_set_link_icon";
  ALTER TABLE "public"."pages_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum_pages_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum_pages_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum_pages_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."pages_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_pages_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum_pages_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."pages_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_pages_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum_pages_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."pages_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum_pages_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum_pages_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."pages_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum_pages_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum_pages_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."pages_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_pages_blocks_gallery_link_icon" USING "link_icon"::"public"."enum_pages_blocks_gallery_link_icon";
  ALTER TABLE "public"."pages_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_pages_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum_pages_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."pages_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_pages_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum_pages_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."pages_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum_pages_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum_pages_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."pages_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_pages_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum_pages_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."pages_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum_pages_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum_pages_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."pages_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_map_pins_icon";
  CREATE TYPE "public"."enum_pages_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_map_pins_icon" USING "icon"::"public"."enum_pages_blocks_map_pins_icon";
  ALTER TABLE "public"."pages_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."pages_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum_pages_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum_pages_blocks_news_snippets_news_set_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum__pages_v_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum__pages_v_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."_pages_v_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum__pages_v_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."_pages_v_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum__pages_v_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."_pages_v_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum__pages_v_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum__pages_v_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_gallery_link_icon" USING "link_icon"::"public"."enum__pages_v_blocks_gallery_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum__pages_v_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum__pages_v_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum__pages_v_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."_pages_v_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum__pages_v_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."_pages_v_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum__pages_v_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."_pages_v_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_map_pins_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_map_pins_icon" USING "icon"::"public"."enum__pages_v_blocks_map_pins_icon";
  ALTER TABLE "public"."_pages_v_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."_pages_v_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum__pages_v_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum__pages_v_blocks_news_snippets_news_set_link_icon";
  ALTER TABLE "public"."globalheader_nav_items" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_globalheader_nav_items_link_icon";
  CREATE TYPE "public"."enum_globalheader_nav_items_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."globalheader_nav_items" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_globalheader_nav_items_link_icon" USING "link_icon"::"public"."enum_globalheader_nav_items_link_icon";
  ALTER TABLE "public"."globalheader_cta_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_globalheader_cta_buttons_link_icon";
  CREATE TYPE "public"."enum_globalheader_cta_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."globalheader_cta_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_globalheader_cta_buttons_link_icon" USING "link_icon"::"public"."enum_globalheader_cta_buttons_link_icon";
  ALTER TABLE "public"."globalfooter_bottom_links" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_globalfooter_bottom_links_link_icon";
  CREATE TYPE "public"."enum_globalfooter_bottom_links_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."globalfooter_bottom_links" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_globalfooter_bottom_links_link_icon" USING "link_icon"::"public"."enum_globalfooter_bottom_links_link_icon";
  ALTER TABLE "public"."flatsstoone" ALTER COLUMN "gallery_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flats_gallery_link_icon";
  CREATE TYPE "public"."enum_flats_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flatsstoone" ALTER COLUMN "gallery_link_icon" SET DATA TYPE "public"."enum_flats_gallery_link_icon" USING "gallery_link_icon"::"public"."enum_flats_gallery_link_icon";
  ALTER TABLE "public"."flDet_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_flDet_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum_flDet_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."flDet_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_flDet_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum_flDet_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."flDet_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum_flDet_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum_flDet_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum_flDet_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."flDet_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_flDet_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum_flDet_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."flDet_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_flDet_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum_flDet_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."flDet_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum_flDet_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum_flDet_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."flDet_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum_flDet_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."flDet_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_flDet_blocks_gallery_link_icon" USING "link_icon"::"public"."enum_flDet_blocks_gallery_link_icon";
  ALTER TABLE "public"."flDet_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum_flDet_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum_flDet_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."flDet_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_flDet_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum_flDet_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."flDet_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum_flDet_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum_flDet_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."flDet_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_map_pins_icon";
  CREATE TYPE "public"."enum_flDet_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_flDet_blocks_map_pins_icon" USING "icon"::"public"."enum_flDet_blocks_map_pins_icon";
  ALTER TABLE "public"."flDet_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."flDet_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum_flDet_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum_flDet_blocks_news_snippets_news_set_link_icon";
  ALTER TABLE "public"."newsDet_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_banner" ALTER COLUMN "banner_button_icon" SET DATA TYPE "public"."enum_newsDet_blocks_banner_banner_button_icon" USING "banner_button_icon"::"public"."enum_newsDet_blocks_banner_banner_button_icon";
  ALTER TABLE "public"."newsDet_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_features_features_with_title" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_newsDet_blocks_features_features_with_title_feature_icon" USING "feature_icon"::"public"."enum_newsDet_blocks_features_features_with_title_feature_icon";
  ALTER TABLE "public"."newsDet_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_features_features_uppercase" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_newsDet_blocks_features_features_uppercase_feature_icon" USING "feature_icon"::"public"."enum_newsDet_blocks_features_features_uppercase_feature_icon";
  ALTER TABLE "public"."newsDet_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_features" ALTER COLUMN "features_settings_link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_features_features_settings_link_icon" USING "features_settings_link_icon"::"public"."enum_newsDet_blocks_features_features_settings_link_icon";
  ALTER TABLE "public"."newsDet_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_flats_snippets" ALTER COLUMN "flats_set_link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon" USING "flats_set_link_icon"::"public"."enum_newsDet_blocks_flats_snippets_flats_set_link_icon";
  ALTER TABLE "public"."newsDet_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_gallery_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_gallery_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_gallery" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_gallery_link_icon" USING "link_icon"::"public"."enum_newsDet_blocks_gallery_link_icon";
  ALTER TABLE "public"."newsDet_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_hero_main_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_hero_main_buttons_link_icon" USING "link_icon"::"public"."enum_newsDet_blocks_hero_main_buttons_link_icon";
  ALTER TABLE "public"."newsDet_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_hero_secondary_buttons" ALTER COLUMN "link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon" USING "link_icon"::"public"."enum_newsDet_blocks_hero_secondary_buttons_link_icon";
  ALTER TABLE "public"."newsDet_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_highlighted_text_buttons" ALTER COLUMN "button_icon" SET DATA TYPE "public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon" USING "button_icon"::"public"."enum_newsDet_blocks_highlighted_text_buttons_button_icon";
  ALTER TABLE "public"."newsDet_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_img_content_person_bullets" ALTER COLUMN "feature_icon" SET DATA TYPE "public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon" USING "feature_icon"::"public"."enum_newsDet_blocks_img_content_person_bullets_feature_icon";
  ALTER TABLE "public"."newsDet_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_img_content" ALTER COLUMN "accordion_link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_img_content_accordion_link_icon" USING "accordion_link_icon"::"public"."enum_newsDet_blocks_img_content_accordion_link_icon";
  ALTER TABLE "public"."newsDet_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_map_pins_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_map_pins_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_map_pins" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_newsDet_blocks_map_pins_icon" USING "icon"::"public"."enum_newsDet_blocks_map_pins_icon";
  ALTER TABLE "public"."newsDet_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon";
  CREATE TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  ALTER TABLE "public"."newsDet_blocks_news_snippets" ALTER COLUMN "news_set_link_icon" SET DATA TYPE "public"."enum_newsDet_blocks_news_snippets_news_set_link_icon" USING "news_set_link_icon"::"public"."enum_newsDet_blocks_news_snippets_news_set_link_icon";
  DROP TYPE "public"."enum_share_blocks_map_pins_position";
  DROP TYPE "public"."enum_share_blocks_map_pins_color";
  DROP TYPE "public"."enum_pages_blocks_map_pins_position";
  DROP TYPE "public"."enum_pages_blocks_map_pins_color";
  DROP TYPE "public"."enum__pages_v_blocks_map_pins_position";
  DROP TYPE "public"."enum__pages_v_blocks_map_pins_color";
  DROP TYPE "public"."enum_flDet_blocks_map_pins_position";
  DROP TYPE "public"."enum_flDet_blocks_map_pins_color";
  DROP TYPE "public"."enum_newsDet_blocks_map_pins_position";
  DROP TYPE "public"."enum_newsDet_blocks_map_pins_color";`)
}
