import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_share_blocks_content_content_settings_link_type" AS ENUM('internal', 'external');
  CREATE TYPE "public"."enum_share_blocks_content_content_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'metro', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  CREATE TYPE "public"."enum_share_blocks_content_content_settings_link_relation" AS ENUM('pages', 'flats', 'news', 'documents', 'anchor');
  CREATE TYPE "public"."enum_share_blocks_content_content_settings_link_appearance" AS ENUM('primary', 'secondary');
  CREATE TYPE "public"."enum_pages_blocks_content_content_settings_link_type" AS ENUM('internal', 'external');
  CREATE TYPE "public"."enum_pages_blocks_content_content_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'metro', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  CREATE TYPE "public"."enum_pages_blocks_content_content_settings_link_relation" AS ENUM('pages', 'flats', 'news', 'documents', 'anchor');
  CREATE TYPE "public"."enum_pages_blocks_content_content_settings_link_appearance" AS ENUM('primary', 'secondary');
  CREATE TYPE "public"."enum__pages_v_blocks_content_content_settings_link_type" AS ENUM('internal', 'external');
  CREATE TYPE "public"."enum__pages_v_blocks_content_content_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'metro', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  CREATE TYPE "public"."enum__pages_v_blocks_content_content_settings_link_relation" AS ENUM('pages', 'flats', 'news', 'documents', 'anchor');
  CREATE TYPE "public"."enum__pages_v_blocks_content_content_settings_link_appearance" AS ENUM('primary', 'secondary');
  CREATE TYPE "public"."enum_flDet_blocks_content_content_settings_link_type" AS ENUM('internal', 'external');
  CREATE TYPE "public"."enum_flDet_blocks_content_content_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'metro', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  CREATE TYPE "public"."enum_flDet_blocks_content_content_settings_link_relation" AS ENUM('pages', 'flats', 'news', 'documents', 'anchor');
  CREATE TYPE "public"."enum_flDet_blocks_content_content_settings_link_appearance" AS ENUM('primary', 'secondary');
  CREATE TYPE "public"."enum_newsDet_blocks_content_content_settings_link_type" AS ENUM('internal', 'external');
  CREATE TYPE "public"."enum_newsDet_blocks_content_content_settings_link_icon" AS ENUM('bike', 'cart', 'hospital', 'cheers', 'maskHappy', 'park', 'road', 'train', 'trainRegional', 'tram', 'metro', 'download', 'file', 'hand', 'wallet', 'zero', 'percentage', 'magnifyingGlass', 'leaf', 'lightBulb', 'drop', 'flash', 'phone', 'mail', 'facebook', 'instagram', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat');
  CREATE TYPE "public"."enum_newsDet_blocks_content_content_settings_link_relation" AS ENUM('pages', 'flats', 'news', 'documents', 'anchor');
  CREATE TYPE "public"."enum_newsDet_blocks_content_content_settings_link_appearance" AS ENUM('primary', 'secondary');
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_heading" jsonb;
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_type" "enum_share_blocks_content_content_settings_link_type" DEFAULT 'internal';
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_new_tab" boolean;
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_has_anchor" boolean;
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_dark_button" boolean;
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_icon_only" boolean DEFAULT false;
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_icon_position" "icnPos" DEFAULT 'left';
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_icon" "enum_share_blocks_content_content_settings_link_icon";
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_label" varchar;
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_relation" "enum_share_blocks_content_content_settings_link_relation" DEFAULT 'pages';
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_url" varchar;
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_anchor_to" varchar;
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_settings_link_appearance" "enum_share_blocks_content_content_settings_link_appearance" DEFAULT 'primary';
  ALTER TABLE "share_blocks_content" ADD COLUMN "content_block" jsonb;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_heading" jsonb;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_type" "enum_pages_blocks_content_content_settings_link_type" DEFAULT 'internal';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_new_tab" boolean;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_has_anchor" boolean;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_dark_button" boolean;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_icon_only" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_icon_position" "icnPos" DEFAULT 'left';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_icon" "enum_pages_blocks_content_content_settings_link_icon";
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_label" varchar;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_relation" "enum_pages_blocks_content_content_settings_link_relation" DEFAULT 'pages';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_url" varchar;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_anchor_to" varchar;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_settings_link_appearance" "enum_pages_blocks_content_content_settings_link_appearance" DEFAULT 'primary';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content_block" jsonb;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_heading" jsonb;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_type" "enum__pages_v_blocks_content_content_settings_link_type" DEFAULT 'internal';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_has_anchor" boolean;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_dark_button" boolean;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_icon_only" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_icon_position" "icnPos" DEFAULT 'left';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_icon" "enum__pages_v_blocks_content_content_settings_link_icon";
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_label" varchar;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_relation" "enum__pages_v_blocks_content_content_settings_link_relation" DEFAULT 'pages';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_url" varchar;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_anchor_to" varchar;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_settings_link_appearance" "enum__pages_v_blocks_content_content_settings_link_appearance" DEFAULT 'primary';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content_block" jsonb;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_heading" jsonb;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_type" "enum_flDet_blocks_content_content_settings_link_type" DEFAULT 'internal';
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_new_tab" boolean;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_has_anchor" boolean;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_dark_button" boolean;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_icon_only" boolean DEFAULT false;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_icon_position" "icnPos" DEFAULT 'left';
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_icon" "enum_flDet_blocks_content_content_settings_link_icon";
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_label" varchar;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_relation" "enum_flDet_blocks_content_content_settings_link_relation" DEFAULT 'pages';
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_url" varchar;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_anchor_to" varchar;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_settings_link_appearance" "enum_flDet_blocks_content_content_settings_link_appearance" DEFAULT 'primary';
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content_block" jsonb;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_heading" jsonb;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_type" "enum_newsDet_blocks_content_content_settings_link_type" DEFAULT 'internal';
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_new_tab" boolean;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_has_anchor" boolean;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_dark_button" boolean;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_icon_only" boolean DEFAULT false;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_icon_position" "icnPos" DEFAULT 'left';
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_icon" "enum_newsDet_blocks_content_content_settings_link_icon";
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_label" varchar;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_relation" "enum_newsDet_blocks_content_content_settings_link_relation" DEFAULT 'pages';
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_url" varchar;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_anchor_to" varchar;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_settings_link_appearance" "enum_newsDet_blocks_content_content_settings_link_appearance" DEFAULT 'primary';
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content_block" jsonb;
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "share_blocks_content" ADD COLUMN "content" jsonb;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "content" jsonb;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "content" jsonb;
  ALTER TABLE "flDet_blocks_content" ADD COLUMN "content" jsonb;
  ALTER TABLE "newsDet_blocks_content" ADD COLUMN "content" jsonb;
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_heading";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_type";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_new_tab";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_has_anchor";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_dark_button";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_only";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_position";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_label";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_relation";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_url";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_anchor_to";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_appearance";
  ALTER TABLE "share_blocks_content" DROP COLUMN IF EXISTS "content_block";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_heading";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_type";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_new_tab";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_has_anchor";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_dark_button";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_only";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_position";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_label";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_relation";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_url";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_anchor_to";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_appearance";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "content_block";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_heading";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_type";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_new_tab";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_has_anchor";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_dark_button";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_only";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_position";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_label";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_relation";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_url";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_anchor_to";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_appearance";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "content_block";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_heading";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_type";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_new_tab";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_has_anchor";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_dark_button";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_only";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_position";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_label";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_relation";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_url";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_anchor_to";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_appearance";
  ALTER TABLE "flDet_blocks_content" DROP COLUMN IF EXISTS "content_block";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_heading";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_type";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_new_tab";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_has_anchor";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_dark_button";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_only";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon_position";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_icon";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_label";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_relation";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_url";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_anchor_to";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_settings_link_appearance";
  ALTER TABLE "newsDet_blocks_content" DROP COLUMN IF EXISTS "content_block";
  DROP TYPE "public"."enum_share_blocks_content_content_settings_link_type";
  DROP TYPE "public"."enum_share_blocks_content_content_settings_link_icon";
  DROP TYPE "public"."enum_share_blocks_content_content_settings_link_relation";
  DROP TYPE "public"."enum_share_blocks_content_content_settings_link_appearance";
  DROP TYPE "public"."enum_pages_blocks_content_content_settings_link_type";
  DROP TYPE "public"."enum_pages_blocks_content_content_settings_link_icon";
  DROP TYPE "public"."enum_pages_blocks_content_content_settings_link_relation";
  DROP TYPE "public"."enum_pages_blocks_content_content_settings_link_appearance";
  DROP TYPE "public"."enum__pages_v_blocks_content_content_settings_link_type";
  DROP TYPE "public"."enum__pages_v_blocks_content_content_settings_link_icon";
  DROP TYPE "public"."enum__pages_v_blocks_content_content_settings_link_relation";
  DROP TYPE "public"."enum__pages_v_blocks_content_content_settings_link_appearance";
  DROP TYPE "public"."enum_flDet_blocks_content_content_settings_link_type";
  DROP TYPE "public"."enum_flDet_blocks_content_content_settings_link_icon";
  DROP TYPE "public"."enum_flDet_blocks_content_content_settings_link_relation";
  DROP TYPE "public"."enum_flDet_blocks_content_content_settings_link_appearance";
  DROP TYPE "public"."enum_newsDet_blocks_content_content_settings_link_type";
  DROP TYPE "public"."enum_newsDet_blocks_content_content_settings_link_icon";
  DROP TYPE "public"."enum_newsDet_blocks_content_content_settings_link_relation";
  DROP TYPE "public"."enum_newsDet_blocks_content_content_settings_link_appearance";`)
}
